name: Build Legacy macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup legacy build
        working-directory: virtual-studio-agent
        run: cp package-legacy.json package.json

      - name: Install
        working-directory: virtual-studio-agent
        run: npm install --legacy-peer-deps

      - name: Build
        working-directory: virtual-studio-agent
        run: npm run build:mac
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Rename
        working-directory: virtual-studio-agent/dist
        run: mv *.zip Virtual.Studio.Agent-legacy.zip

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: legacy-macos-10.11
          path: virtual-studio-agent/dist/Virtual.Studio.Agent-legacy.zip
